// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCachyI-cxDaDHYhrsGTURf4R3m2K_ze_4',
    appId: '1:741245704812:web:586a4f92ad1a041bfbd649',
    messagingSenderId: '741245704812',
    projectId: 'clroom-55a59',
    authDomain: 'clroom-55a59.firebaseapp.com',
    storageBucket: 'clroom-55a59.firebasestorage.app',
    measurementId: 'G-JEBFZRCK1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjX3fuDnXpZykxTmukHsT6EGZPN-TKfY8',
    appId: '1:741245704812:android:9f5152af59513784fbd649',
    messagingSenderId: '741245704812',
    projectId: 'clroom-55a59',
    storageBucket: 'clroom-55a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWUxGKiA2XplavahmP1O3Yk0U9iemSHE',
    appId: '1:741245704812:ios:1396691416f9df3bfbd649',
    messagingSenderId: '741245704812',
    projectId: 'clroom-55a59',
    storageBucket: 'clroom-55a59.firebasestorage.app',
    iosBundleId: 'com.example.gcr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbWUxGKiA2XplavahmP1O3Yk0U9iemSHE',
    appId: '1:741245704812:ios:1396691416f9df3bfbd649',
    messagingSenderId: '741245704812',
    projectId: 'clroom-55a59',
    storageBucket: 'clroom-55a59.firebasestorage.app',
    iosBundleId: 'com.example.gcr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCachyI-cxDaDHYhrsGTURf4R3m2K_ze_4',
    appId: '1:741245704812:web:3fd2248e8749ae7dfbd649',
    messagingSenderId: '741245704812',
    projectId: 'clroom-55a59',
    authDomain: 'clroom-55a59.firebaseapp.com',
    storageBucket: 'clroom-55a59.firebasestorage.app',
    measurementId: 'G-C5BQWTFMWZ',
  );
}
